### ISSUE TITLE
There is no indicator when the number of maxLines has reached

### ISSUE THREAD

**Issue by maxkudla** [arendjr/text-clipper#17]
The indicator is added only in case when `numChars> maxLength`. 
![image](https://user-images.githubusercontent.com/9202221/139073471-3d5bc3d6-bb6b-49b8-9b3e-984c47291eae.png)

But if `numLines > maxLines`, it doesn't happen. It just closes the tags
![image](https://user-images.githubusercontent.com/9202221/139073572-458c1475-def8-46de-946f-a17e23a67a4e.png)

**Comment by arendjr** [comment]
Thanks for the report! This behavior is actually intentional, because it would look kinda weird if there’s a new line with just ellipses, while adding the ellipses to the text before the newline is also weird. However, it does assume there is an additional visual indicator (such as a “Read more” link) so that the truncation is still obvious to the user.

What’s your use case? I can imagine it makes sense to make this behavior configurable.

**Comment by maxkudla** [comment]
Actually the link "Read more" is that case... No link when HTML is clipped by maxLines

**Comment by arendjr** [comment]
Ah, I see. That actually makes sense, but it’s not really how the indicator was intended to be used. In that case, why not write it like this:

```js
let clippedText = clip(text, 80, { maxLines: 3 });
if (clippedText.length < text.length) {
    clippedText += readMoreLink;
}
```

This is very close to how I used it myself (except I’d use JSX to insert the link).

I think this makes for a clearer text experience, because you’ll still get ellipses when the text is clipped mid-paragraph (instead of running straight into the Read more link), while you would get a clean stand-alone Read more link if the text is clipped at a line break.

**Comment by arendjr** [comment]
Please note the [README](https://github.com/arendjr/text-clipper#indicator) also already mentions this behavior:

> Note the indicator is only inserted when the clipping doesn't occur at a line-break.

So I hope the above work-around will suffice for you. Feel free to reopen if it doesn’t.
