### ISSUE TITLE
Extra space is added after word

### ISSUE THREAD

**Issue by AlecRobertson** [arendjr/text-clipper#18]
<img width="241" alt="Screenshot 2022-01-11 at 16 40 53" src="https://user-images.githubusercontent.com/4457688/148984343-cda57833-ba1f-4414-8098-e30716036e4b.png">

This is with HTML set to true, I am finding that a space is added after the word, is it possible to change the output such that the space after the word is not added?

**Comment by janis-veinbergs** [comment]
Just do this:
```
(clip("achievements before we won", 24, { indicator: "" }).trim() + "…"
```

The other question is if whitespace should be automatically trimmed - if it would be implemented in default behavior, it could break someone's code who would expect trimmed text to be exactly `maxLength` characters long. Otherwise it could be a nice non-default option.

**Comment by arendjr** [comment]
Hey, sorry for the late response. I think what @janis-veinbergs provides is a somewhat workable work-around, but I also agree with the original report. Ideally, the space wouldn't be there, and if I remember correctly, the only reason it's still there is because it was somewhat tricky to remove it consistently. Note that the default behavior is already to break at word boundaries, so it's already acceptable to return strings less than `maxLength` characters.

That said, I might indeed want to do a major version bump when I fix this, just in case. Not sure exactly when I have time to pick this up, so if you want to work on this, please let me know. PRs are welcome :)

**Comment by arendjr** [comment]
Better late than never, this is implemented :)
