### ISSUE TITLE
Clipped length is different from max length

### ISSUE THREAD

**Issue by numscrl** [arendjr/text-clipper#4]
I am consistently seeing clipped text who length does not match the max length requested. For example,

`var textClipper = require("text-clipper")`
`var html = "<p>David</p>";`
`textClipper(html, 4, { indicator: "", html: true, breakWords: true} );`

returns the clipped text "Dav". Tried with many other short-ish strings with consistent results. The clipped text is always one character less than requested.

Am I possibly misusing the API in some way?

**Comment by arendjr** [comment]
Thanks for the report! I think this is a genuine bug. Normally, it would make sense to have the clipped text be one character shorter, because space needs to be kept for the indicator, but seeing how you're not using any indicator, I agree the clipped text should just use that extra character.

I'm afraid currently it is hard-coded to reserve exactly one character, but I think it can easily be fixed by changing the initialization of `numChars` at lines 80 and 363. Be my guest to try it out, and if it works, I'd happily apply the PR!

**Comment by arendjr** [comment]
Sorry for the late response! This is now fixed in release 1.2.3!

**Comment by numscrl** [comment]
Thanks!
________________________________
